deploymentStrategy:
  type: RollingUpdate
ssl:
  enabled: true
  enforced: true
dashboard:
  enabled: true
  domain: traefik.nimbus.ddns.me
  ingress:
    tls: 
      - hosts:
        - traefik.nimbus.ddns.me
        secretName: traefik-tls
    annotations:
      certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
rbac:
  enabled: true
