---
- name: Deploy Traefik on cluster
  include_role:
    name: helm
  vars:
    name: "traefik"
    chart: "stable/traefik"
    version: "1.76.0"
    values: "roles/traefik/files/values.yml"
    namespace: "default"
