---
- name: Configure RBAC for Tiller
  k8s:
    state: present
    definition: "{{ lookup('file', 'tiller-rbac.yml') }}"

- name: Install helm
  shell: helm init --service-account tiller --tiller-image=jessestuart/tiller
  changed_when: False

- name: Install Metallb
  include_role:
    name: metallb

- name: Install Traefik
  include_role:
    name: traefik

- name: Install Cert Manager
  include_role:
    name: cert-manager
