---
- name: Deploy Metallb to cluster
  include_role:
    name: helm
  vars:
    name: "metallb"
    chart: "stable/metallb"
    version: "0.11.1"
    values: "roles/metallb/files/values.yml"
    namespace: "metallb"
