- name: Enable IP forwarding
  replace:
    path: /etc/sysctl.conf
    regexp: '^#.*net.ipv4.ip_forward=.*$'
    replace: 'net.ipv4.ip_forward=1'
  become: yes
  register: forwarding
- name: Configure iptables to use Masquerade for outgoing traffic from cluster to eth0
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth1
    jump: MASQUERADE
  become: yes
  register: masquerade
- name: Configure iptables to forward traffic from inside the cluster (eth1) to outside (eth0)
  iptables:
    chain: FORWARD
    in_interface: eth1
    out_interface: eth0
    jump: ACCEPT
  become: yes
  register: outside
- name: Configure iptables to forward from outside the cluster (eth1) to inside (eth0)
  iptables:
    chain: FORWARD
    protocol: tcp
    in_interface: eth0
    out_interface: eth1
    jump: ACCEPT
  become: yes
  register: inside
- name: Forward returning traffic
  iptables:
    chain: FORWARD
    protocol: tcp
    in_interface: eth1
    out_interface: eth0
    jump: ACCEPT
    match: state
    ctstate: ESTABLISHED,RELATED
  become: yes
  register: returning
- name: Configure iptables to map the Kubernetes admin port (6443) on the master node - DNAT
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination: 192.168.178.42
    destination_port: 6443
    jump: DNAT
    to_destination: 10.64.91.35:6443
    action: insert
  become: yes
  register: admindnat
- name: Configure iptables to map the Kubernetes admin port (6443) on the master node - SNAT
  iptables:
    table: nat
    chain: POSTROUTING
    protocol: tcp
    destination: 10.64.91.35
    destination_port: 6443
    jump: SNAT
    to_source: 10.64.0.1
    action: insert
  become: yes
  register: adminsnat
- name: Configure iptables to map port 443 on the external node port 443 - DNAT
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination: 192.168.178.42
    destination_port: 443
    jump: DNAT
    to_destination: 10.64.91.32:443
    action: insert
  become: yes
  register: httpsdnat
- name: Configure iptables to map port 443 on the external node port 443 - SNAT
  iptables:
    table: nat
    chain: POSTROUTING
    protocol: tcp
    destination: 10.64.91.32
    destination_port: 443
    jump: SNAT
    to_source: 10.64.0.1
    action: insert
  become: yes
  register: httpssnat
- name: Configure iptables to map port 80 on the external node port 80 - DNAT
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination: 192.168.178.42
    destination_port: 80
    jump: DNAT
    to_destination: 10.64.91.32:80
    action: insert
  become: yes
  register: httpdnat
- name: Configure iptables to map port 80 on the external node port 80 - SNAT
  iptables:
    table: nat
    chain: POSTROUTING
    protocol: tcp
    destination: 10.64.91.32
    destination_port: 80
    jump: SNAT
    to_source: 10.64.0.1
    action: insert
  become: yes
  register: httpsnat
- name: Make iptables persistent
  apt:
    name: iptables-persistent
    update_cache: yes
  become: yes
  register: iptablespersistent
- name: Save iptables
  shell: iptables-save > /etc/iptables/rules.v4
  become: yes
  when: forwarding.changed or masquerade.changed or outside.changed or inside.changed or returning.changed or admindnat.changed or adminsnat.changed or httpsdnat.changed or httpssnat.changed or httpdnat.changed or httpsnat.changed
- name: Reboot the router for changes to take effect
  reboot:
  become: true
  when: forwarding.changed or masquerade.changed or outside.changed or inside.changed or returning.changed or admindnat.changed or adminsnat.changed or httpsdnat.changed or httpssnat.changed or httpdnat.changed or httpsnat.changed

