---
- name: Init Kubernetes Master
  shell: kubeadm init --token {{ kubeadm_token }} --apiserver-cert-extra-sans {{ groups['router'][0] }}
  register: kubeadm_init

- name: Create Kubernetes config directory
  file:
    path: /root/.kube/
    state: directory
    owner: root
    group: root
    mode: 0755
  when: kubeadm_init

- name: Copy admin.conf to config directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: 0755
    remote_src: yes
    backup: yes
  when: kubeadm_init

- name: Fetch kube config
  fetch:
    src: /root/.kube/config
    dest: ~/.kube/
    flat: yes
  when: kubeadm_init

- name: Install Weave (Networking)
  shell: "kubectl apply -f \"https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&env.IPALLOC_RANGE=10.32.0.0/16\""
  when: kubeadm_init
