---
- name: Configure Router for DNS resolving
  copy:
    src: ../files/resolv.conf
    dest: /etc/resolv.conf
    backup: yes
  become: yes
- name: Trust Kubernetes APT key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  become: yes
- name: Add APT Kubernetes Repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
  become: yes
- name: Install kubeadm
  apt:
    name: kubeadm={{ kubeadm_version }}
    update_cache: yes
  become: yes
- name: Install open-iscsi
  apt:
    name: open-iscsi
    update_cache: yes
  become: yes